# Generated by Django 6.0.5 on 2026-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.CharField(choices=[('love', '😍 Love Atya'), ('helpful', '🙂 Helpful'), ('average', '😐 Average'), ('missing', '😕 Missing Features'), ('bug', '🐞 Found a Bug')], max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('data', 'Data Correction'), ('ui', 'UI / Design Feedback')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
